version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # Expose ports for backend and frontend if needed for local preview within Codespace
    # ports:
    #   - "3002:3002" # Backend port
    #   - "5177:5177" # Frontend dev server port

